### ISSUE TITLE
autoprefixer.browsers setting seems ignored

### ISSUE THREAD

**Issue by druellan** [mrmlnc/vscode-autoprefixer#1]
Hi. First, thanks for this extension.

I'm trying to autoprefix a file using this settings:
`"autoprefixer.browsers": [ "last 4 versions", "ie >= 9", "> 5%" ]`

But looks like the plugin is ignoring them.

For example I have this line:
`transform: translate(0,0);`

By the options above, the end result should be something like this:
```
-webkit-transform: translate(0, 0);
-ms-transform: translate(0, 0);
transform: translate(0, 0);
```

But I get this result:
```
-webkit-transform: translate(0, 0);
transform: translate(0, 0);
```

Code version 1.3.1 Windows 7 64bits
Autoprefixer version 6.3.7

**Comment by mrmlnc** [comment]
Hi, @druellan,

Thanks for the well documented Issue.

Sorry for this, my mistake. Fixed in version 1.0.3.
