### ISSUE TITLE
VS Code autoprefix extension - unknown browser query

### ISSUE THREAD

**Issue by alljamin** [mrmlnc/vscode-autoprefixer#100]
Is it in plans to update to the latest commands from Browserslist?

The valid command below is not supported by VS Code extension:
```
{
"autoprefixer.browsers": [
        "cover 99.5%"
    ]
}
```

Returns:

```
[Autoprefixer]

BrowserslistError: Unknown browser query `cover 99.5%`
```

Feedback from Autoprefix contributors - https://github.com/postcss/autoprefixer/issues/1154

**Comment by mrmlnc** [comment]
Will be fixed in today's version of the plugin.

JFYI: You can use the local Autoprefixer as described in the [documentation](https://github.com/mrmlnc/vscode-autoprefixer#supported-settings).
