### ISSUE TITLE
Feature request External file && minify

### ISSUE THREAD

**Issue by rsepierre** [mrmlnc/vscode-autoprefixer#104]
Hi, my idear would be that you could have the option to prefix in a separate file : 

styles.css > prefixed.style.css

and maybe you can minify too

styles.css > prefixed.style.min.css ( could just be .min)

This way your "style.css" is PURE css. and the prefixed or .min file is your production file. 

with auto minify/prefix on external file when you save the main file if a .min or .prefixed file already exists.

**Comment by mrmlnc** [comment]
IMHO, this is beyond the scope of this plugin — just add prefixes. In this case, it is better to use build systems like gulp, webpack, etc…
