### ISSUE TITLE
There is an error when I use it in VS Code

### ISSUE THREAD

**Issue by 1vanLuo** [mrmlnc/vscode-autoprefixer#110]
I installed the extension in my VS Code,
But when I use it the console shows the error
![QQ截图20190828104916](https://user-images.githubusercontent.com/29398278/63830165-0eb0e300-c99e-11e9-9292-dd93a445bdc0.png)
How to fix this?

**Comment by willdante** [comment]
Same here after a fresh install.

**Comment by 1vanLuo** [comment]
Try to use this extension in .css file

**Comment by willdante** [comment]
I've tried it in a .css file and got a different error:

`TypeError: Cannot read property 'syntax' of null`

**Comment by 1vanLuo** [comment]
It's weird, I use it in .css file is ok.

**Comment by willdante** [comment]
I've tried it in the global.css file in a Sapper (Svelte) project.
I will try in a .css file from a more classic setup.

**Comment by mrmlnc** [comment]
Will be fixed with `3.0.0`.
