### ISSUE TITLE
Used this plugin for CSS files in one project and it seems it can not open it in Firefox Mozilla 

### ISSUE THREAD

**Issue by KlaraZdjelarevic** [mrmlnc/vscode-autoprefixer#111]
Looks like it is not able to open in Mozilla browser, it opens up but witouth any .css files. The file is on an external disk. Is there a way to fix it?

Thank you in advance. 

Kind regards,

Klara Z.

**Comment by mrmlnc** [comment]
Hello, @KlaraZdjelarevic,

Unfortunately, I don't understand what you're talking about. Can you give the steps so that I can reproduce the problem?

**Comment by mrmlnc** [comment]
Close this issue as an outdated.
