### ISSUE TITLE
ignore prefix on sass files but work on css compiled files

### ISSUE THREAD

**Issue by solomonakp** [mrmlnc/vscode-autoprefixer#115]
hello, 
      it's a wonderful plugin that help a lot. Is it possible for me to disable the prefixer on my sass files but still have it prefix my css compiled files.

**Comment by mrmlnc** [comment]
Hello, @solomonakp,

For this case, you can use any builder like gulp, webpack and etc. This plugin is only needed for the simplest file processing.

**Comment by mrmlnc** [comment]
Outdated issue.

If you use the `formatOnSave` option then you can use `ignoreFiles` to ignore any files with glob patterns.
