### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by earboleya** [mrmlnc/vscode-autoprefixer#117]
- Issue Type: `Performance`
- Extension Name: `vscode-autoprefixer`
- Extension Version: `3.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\effit\mrmlnc.vscode-autoprefixer-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by YuriiS-68** [comment]
[mrmlnc.vscode-autoprefixer-unresponsive.cpuprofile.txt](https://github.com/mrmlnc/vscode-autoprefixer/files/4499933/mrmlnc.vscode-autoprefixer-unresponsive.cpuprofile.txt)
