### ISSUE TITLE
Autoprefixer attempting to run on all files

### ISSUE THREAD

**Issue by jcollicoat** [mrmlnc/vscode-autoprefixer#119]
- Issue type: `bug`
- Extension Name: `vscode-autoprefixer`
- Extension Version: `3.0.0`
- OS Version: MacOS Catalina 10.15.3
- VSCode Version: 1.43.2

I'm finding that the autoprefixer is attempting to run on all files, instead of just CSS/SCSS. It's started doing this only in the last couple of months (not sure when exactly sorry).

I can still run the prefixer with `ctrl+shift+C` but cannot use Format On Save at the moment, as it throws up this error every time I'm saving a file that isn't CSS/SCSS (screenshot below):
```
[Autoprefixer]
Cannot execute Autoprefixer because there is not supported languages. Supported: LESS, SCSS, PostCSS and CSS.
```
![Screen Shot 2020-04-01 at 12 35 42 PM](https://user-images.githubusercontent.com/28215572/78084675-55275e00-7415-11ea-87b8-eab2671d33df.png)

Any help would be appreciated, cheers.

**Comment by fcngraphics** [comment]
I just started to have the same problem... any clues?

**Comment by ibm-sint** [comment]
Confirming the same issue appears for me.

**Comment by zeinnicholas** [comment]
Yep... Same here. It works nonetheless but it's pretty annoying having the debug panel open every time we save anything.

**Comment by zeinnicholas** [comment]
The issue is fixed! Awesome! Thanks!

**Comment by jcollicoat** [comment]
Thanks for fixing! :)
