### ISSUE TITLE
Failed to load autoprefixer library

### ISSUE THREAD

**Issue by hasinoorit** [mrmlnc/vscode-autoprefixer#121]
It is not showing any error or doing anything when **Autoprefixer: Find External Autoprefixer** is **false**. When it is **true**, it show error 
`[Autoprefixer]
Error: Failed to load autoprefixer library. Please install autoprefixer in your workspace folder using **npm install autoprefixer** or globally using **npm install -g autoprefixer** and then run command again.
	at /home/hasinoor/.vscode/extensions/mrmlnc.vscode-autoprefixer-3.0.1/out/extension.js:2:1575513`

My VSCode details is:

> Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-28-generic snap

Node version: v12.16.3
OS: Ubuntu 20.04 LTS

Note: sublime-autoprefixer is also not working. It may be problem of any dependency.

**Comment by mrmlnc** [comment]
When the `autoprefixer.findExternalAutoprefixer` option is `false` then the extension uses the internal version of autoprefixer. If `true` — the extension trying to find external version of autoprefixer in the current workspace or global npm directory.

* Are there any steps to reproduce the problem?
* Help → Toggle Developer Tools shows any errors related to extension?

**Comment by hasinoorit** [comment]
No Error showing in developer tools. Actually its not problem of your plugin. May be it is bug of postcss. Because i have try to check it using cli tools command **npx postcss style.css --use autoprefixer -o styles.css**. It generate files but don't add any prefix. You can close this issue.Thank you.

**Comment by 0x44454c** [comment]
I am also facing same problem! 
```
[Autoprefixer]
Error: Failed to load autoprefixer library. Please install autoprefixer in your workspace folder using **npm install autoprefixer** or globally using **npm install -g autoprefixer** and then run command again.
	at /home/delusion/.vscode/extensions/mrmlnc.vscode-autoprefixer-3.0.1/out/extension.js:2:1575513
```
Although I have installed autoprefixer and postcss globally it's showing same error.
