### ISSUE TITLE
Stop autoprefixing grid

### ISSUE THREAD

**Issue by samuraki** [mrmlnc/vscode-autoprefixer#123]
I wrote "autoprefixer.grid": "autoplace" on settings.json, but grid autoprefixing doesn't work.
If I changed this code "grid": "autoplace", grid autoprefixing started working.
Is it a bug ? If it's a bug, could you check it, please?

thanks

### Environment

* VS Code version: 1.45.1
* Autoprefixer plugin version: 3.0.1
* Operating System: windows10

### Autoprefixer config

"autoprefixer.options": {
    "browsers": ["last 4 versions", "ie >= 9", "> 5%"],
    "grid": "autoplace"
}

**Comment by mrmlnc** [comment]
Thanks for the issue :tada:

No, it's not a bug — this is a breaking changes in [`3.0.0`](https://github.com/mrmlnc/vscode-autoprefixer/releases/tag/3.0.0).

**Comment by samuraki** [comment]
Oops! I didn't notice the specifications had changed!!
I was just using older codes.

"autoprefixer.options": {
  "autoprefixer.grid": "autoplace",
  "autoprefixer.browsers": ["last 4 versions"]
},

Thank you for responding🎉🎉
If someone has same problem, I want you to tell it! And...

I want you to change error messages for issue#122 !
I thought the Node path has some problem from this error messages😢

Error: Failed to load autoprefixer library. Please install autoprefixer in your workspace folder using **npm install autoprefixer** or globally using **npm install -g autoprefixer** and then run command again.
