### ISSUE TITLE
ignore .scss and .sass files

### ISSUE THREAD

**Issue by ThisNameWasTaken** [mrmlnc/vscode-autoprefixer#93]
Hi, I was thinking if there is a way to stop the autoprefixer from prefixing certain (types of) files. If not can you add such a feature? @mrmlnc

**Comment by mrmlnc** [comment]
Will be fixed with `3.0.0` by `autoprefixer.ignoreFiles` option.

**Comment by digiage** [comment]
Hello. For me it still prefixes scss files on save. I have this settings:

"autoprefixer.formatOnSave": true,
"autoprefixer.ignoreFiles": ["*.scss"]

I have tried to reinstall the the extension, disable, enable, but the result is still the same.

One more insight. It actually prefixes only scss and ignores the css files.

I believe the Autoprefixer addon worked well before without prefixing scss, but suddenly started to do this. I can't imagine prefixing scss would be default setting, as it is not very comfortable to have to change the values in scss in many places after it applies prefixes.
